[colors]
foreground = "#f2f4f8"
background = "#161616"
cursor_bg = "#f2f4f8"
cursor_border = "#f2f4f8"
cursor_fg = "#161616"
selection_bg = "#f2f4f8"
selection_fg = "#161616"

ansi = ["#393939", "#ee5396", "#42be64", "#78a9ff", "#33b1ff", "#be95ff", "#08bdba", "#f2f4f8"]
brights = ["#525252", "#ee5396", "#42be64", "#78a9ff", "#33b1ff", "#be95ff", "#08bdba", "#ffffff"]

# scheme: "IBM Carbon Dark"
# author: "shaunsingh/IBM"
# base00: "#161616" 
# base01: "#262626" 
# base02: "#393939" 
# base03: "#525252" 
# base04: "#dde1e6" 
# base05: "#f2f4f8" 
# base06: "#ffffff" 
# base07: "#08bdba"
# base08: "#3ddbd9" 
# base09: "#78a9ff" 
# base0A: "#ee5396" 
# base0B: "#33b1ff" 
# base0C: "#ff7eb6" 
# base0D: "#42be65" 
# base0E: "#be95ff" 
# base0F: "#82cfff"
